sawtooth_use_nightly_repo: false
sawtooth_repo_keyserver: hkp://keyserver.ubuntu.com:80
sawtooth_repo_key: 8AA7AF1F1091A5FD
sawtooth_repo: ubuntu/chime/stable
sawtooth_consensus_engine: Devmode
sawtooth_user_key_name: vagrant
