IMAGE_NAME = "bento/ubuntu-18.04"
MEM = 1024
CPU = 1
NODES_NBR = 4
NODE_NETWORK_BASE = "10.0.0"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = MEM
        v.cpus = CPU
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    (1..NODES_NBR).each do |i|
        config.vm.define "sawtooth-node-#{i}" do |worker|
            worker.vm.box = IMAGE_NAME
            worker.vm.network "private_network", ip: "#{NODE_NETWORK_BASE}.#{i + 10}"
            worker.vm.hostname = "sawtooth-node-#{i}"

            worker.vm.network "forwarded_port", guest: 8800, host: "#{i}8800"
            worker.vm.network "forwarded_port", guest: 4004, host: "#{i}4004"
            worker.vm.network "forwarded_port", guest: 5050, host: "#{i}5050"
            worker.vm.network "forwarded_port", guest: 8008, host: "#{i}8008"
            worker.vm.network "forwarded_port", guest: 8086, host: "#{i}8086"
            worker.vm.network "forwarded_port", guest: 3000, host: "#{i}3000"
        end
    end

    config.vm.provision "shell", inline: <<-SHELL
      apt-get -qq install -y avahi-daemon libnss-mdns
    SHELL
end
