---
- name: "Generate user key for Sawtooth"
  become: false
  command: sawtooth keygen {{ sawtooth_user_key_name }} creates="/home/{{ ansible_user }}/.sawtooth/keys/{{ sawtooth_user_key_name }}.priv"

- name: "Generate the key for the validator, which runs as root"
  become_user: root
  command: sawadm keygen creates="/etc/sawtooth/keys/validator.priv"
