---
- name: "Start and enable the Sawtooth Services"
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - sawtooth-validator
    - sawtooth-rest-api
    - sawtooth-settings-tp
    - sawtooth-intkey-tp-python

- name: "Start and enable the non Devmode Sawtooth Services"
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - sawtooth-identity-tp
  when: sawtooth_consensus_engine != "Devmode"

- name: "[PBFT] Start the consensus-related components as services."
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - sawtooth-pbft-engine
  when: sawtooth_consensus_engine == "PBFT"

- name: "[PoET] Start the consensus-related components as services."
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - sawtooth-poet-validator-registry-tp
    - sawtooth-poet-engine
  when: sawtooth_consensus_engine == "PoET"
